"""Synthetic general industrial-maintenance knowledge chunks."""


DOCUMENT_CHUNKS = [
    {
        "id": 1,
        "source": "synthetic-maintenance-guide",
        "title": "Motor drive-end bearing vibration",
        "document_section": "Bearings",
        "equipment_type": "Electric motor",
        "content": "High vibration concentrated at an electric motor drive-end bearing can indicate bearing wear, looseness, poor lubrication, or load transmitted through the coupling. Compare radial and axial readings, inspect the bearing condition, and verify the mounting before returning the motor to service.",
    },
    {
        "id": 2,
        "source": "synthetic-maintenance-guide",
        "title": "Bearing temperature rise",
        "document_section": "Bearings",
        "equipment_type": "Electric motor",
        "content": "A rising bearing temperature may result from excess grease, insufficient lubrication, contamination, overload, or incorrect internal clearance. Trend temperature with load and vibration, inspect lubricant condition, and avoid adding grease without confirming the lubrication requirement.",
    },
    {
        "id": 3,
        "source": "synthetic-maintenance-guide",
        "title": "Shaft and coupling misalignment",
        "document_section": "Alignment",
        "equipment_type": "Rotating equipment",
        "content": "Angular or offset shaft misalignment commonly produces elevated axial vibration, coupling heating, and repeated bearing or seal distress. Check soft foot first, then measure and correct coupling alignment under representative operating conditions.",
    },
    {
        "id": 4,
        "source": "synthetic-maintenance-guide",
        "title": "Motor vibration assessment",
        "document_section": "Condition monitoring",
        "equipment_type": "Electric motor",
        "content": "When motor vibration increases, record direction, frequency, load, speed, and the difference between drive-end and non-drive-end measurements. Inspect foundation bolts, alignment, balance, bearings, and driven-machine forces before replacing components.",
    },
    {
        "id": 5,
        "source": "synthetic-maintenance-guide",
        "title": "Electric motor overheating",
        "document_section": "Temperature",
        "equipment_type": "Electric motor",
        "content": "Motor temperature rise can follow overload, voltage imbalance, blocked ventilation, frequent starts, or bearing friction. Compare phase current, check cooling passages and fan condition, and correlate winding and bearing temperatures with operating load.",
    },
    {
        "id": 6,
        "source": "synthetic-maintenance-guide",
        "title": "Recognizing centrifugal pump cavitation",
        "document_section": "Hydraulics",
        "equipment_type": "Centrifugal pump",
        "content": "Cavitation often sounds like crackling gravel inside a centrifugal pump and may cause fluctuating discharge pressure, vibration, and loss of capacity. Check suction restrictions, liquid level, inlet valve position, temperature, and available suction head before prolonged operation.",
    },
    {
        "id": 7,
        "source": "synthetic-maintenance-guide",
        "title": "Pump suction-side checks",
        "document_section": "Hydraulics",
        "equipment_type": "Centrifugal pump",
        "content": "For unstable pump flow, inspect the suction strainer, piping high points, air leaks, tank level, and partially closed valves. A restricted or aerated inlet can reduce suction pressure and create noise similar to cavitation.",
    },
    {
        "id": 8,
        "source": "synthetic-maintenance-guide",
        "title": "Mechanical seal leakage",
        "document_section": "Seals",
        "equipment_type": "Centrifugal pump",
        "content": "Mechanical seal leakage can result from damaged faces, dry running, contamination, shaft runout, misalignment, or incorrect flush conditions. Confirm the leak source and operating conditions before adjustment or seal replacement.",
    },
    {
        "id": 9,
        "source": "synthetic-maintenance-guide",
        "title": "Fan blade buildup and imbalance",
        "document_section": "Balance",
        "equipment_type": "Industrial fan",
        "content": "Dust or process material accumulated unevenly on fan blades shifts rotor mass and creates imbalance vibration. Isolate the fan, clean every blade consistently, inspect for erosion or damage, and verify vibration after restart.",
    },
    {
        "id": 10,
        "source": "synthetic-maintenance-guide",
        "title": "Industrial fan rotor imbalance",
        "document_section": "Balance",
        "equipment_type": "Industrial fan",
        "content": "Rotor imbalance typically produces strong radial vibration at running speed. Check for blade buildup, missing balance weights, bent blades, hub damage, and shaft runout before performing field balancing.",
    },
    {
        "id": 11,
        "source": "synthetic-maintenance-guide",
        "title": "Fan abnormal noise inspection",
        "document_section": "Inspection",
        "equipment_type": "Industrial fan",
        "content": "Abnormal fan noise may come from rubbing, loose guards, worn bearings, turbulent airflow, or damaged blades. Stop equipment if contact is suspected, then inspect clearances, fasteners, bearings, and duct obstructions.",
    },
    {
        "id": 12,
        "source": "synthetic-maintenance-guide",
        "title": "Post-maintenance vibration verification",
        "document_section": "Condition monitoring",
        "equipment_type": "Rotating equipment",
        "content": "After bearing, alignment, cleaning, or balancing work, collect vibration readings at the same locations and operating state used for the baseline. Record speed, load, temperature, and maintenance action so the result can be compared reliably over time.",
    },
]
